### ISSUE TITLE
Support for single files

### ISSUE THREAD

**Issue by cbandy** [vapier/chrome-ext-wicked-good-unarchiver#1]
I'd like to resurrect https://bugs.chromium.org/p/chromium/issues/detail?id=209420.

Is it possible at all to decompress a file that isn't an archive, e.g. `bootable.img.gz`?

**Comment by vapier** [comment]
i've toyed around with implementing this, but libunarchive isn't working quite right.  i tried asking upstream but didn't hear back, and then never got back to it.

https://groups.google.com/d/msg/libarchive-discuss/N8gbV48mz5Y/WvMb-0USHgAJ

**Comment by vapier** [comment]
this is fixed by commit bb29be9ea04e54be73408bab370e9d7ac00af80b.  performance is not great, but libarchive's raw archive format is not great here :/.
